flowchart LR
    blog[["`blog`"]]

    subgraph primary-deps [Primary dependencies]
        plumage{{"`plumage`"}}
        pelican_seo{{"`pelican-seo`"}}
        pelican_search{{"`pelican-search`"}}
        pelican_neighbors{{"`pelican-neighbors`"}}
        pelican_sitemap{{"`pelican-sitemap`"}}
        pelican{{"`pelican`"}}
        markdown_it_py{{"`markdown-it-py`"}}
        typogrify{{"`typogrify`"}}
        pygments{{"`pygments`"}}
    end

    sphinx(["`sphinx`"])
    pelican_myst_reader(["`pelican-myst-reader`"])
    myst_parser(["`myst-parser`"])
    docutils(["`docutils`"])
    requests(["`requests`"])
    sphinxcontrib_bibtex(["`sphinxcontrib-bibtex`"])
    beautifulsoup4(["`beautifulsoup4`"])
    jinja2(["`jinja2`"])
    pybtex(["`pybtex`"])
    anyio(["`anyio`"])
    pybtex_docutils(["`pybtex-docutils`"])
    pyquery(["`pyquery`"])
    pyyaml(["`pyyaml`"])
    rich(["`rich`"])
    colorama(["`colorama`"])
    feedgenerator(["`feedgenerator`"])
    idna(["`idna`"])
    mdit_py_plugins(["`mdit-py-plugins`"])
    packaging(["`packaging`"])
    pelican_webassets(["`pelican-webassets`"])
    python_dateutil(["`python-dateutil`"])
    roman_numerals_py(["`roman-numerals-py`"])
    typing_extensions(["`typing-extensions`"])
    tzdata(["`tzdata`"])
    urllib3(["`urllib3`"])
    watchfiles(["`watchfiles`"])
    alabaster(["`alabaster`"])
    babel(["`babel`"])
    blinker(["`blinker`"])
    certifi(["`certifi`"])
    charset_normalizer(["`charset-normalizer`"])
    cssmin(["`cssmin`"])
    cssselect(["`cssselect`"])
    execnet(["`execnet`"])
    imagesize(["`imagesize`"])
    iniconfig(["`iniconfig`"])
    latexcodec(["`latexcodec`"])
    libsass(["`libsass`"])
    lxml(["`lxml`"])
    markdown(["`markdown`"])
    markdown_word_count(["`markdown-word-count`"])
    markupsafe(["`markupsafe`"])
    mdurl(["`mdurl`"])
    ordered_set(["`ordered-set`"])
    pluggy(["`pluggy`"])
    psutil(["`psutil`"])
    pynpm(["`pynpm`"])
    roman_numerals(["`roman-numerals`"])
    rtoml(["`rtoml`"])
    six(["`six`"])
    smartypants(["`smartypants`"])
    snowballstemmer(["`snowballstemmer`"])
    soupsieve(["`soupsieve`"])
    sphinxcontrib_applehelp(["`sphinxcontrib-applehelp`"])
    sphinxcontrib_devhelp(["`sphinxcontrib-devhelp`"])
    sphinxcontrib_htmlhelp(["`sphinxcontrib-htmlhelp`"])
    sphinxcontrib_jsmath(["`sphinxcontrib-jsmath`"])
    sphinxcontrib_qthelp(["`sphinxcontrib-qthelp`"])
    sphinxcontrib_serializinghtml(["`sphinxcontrib-serializinghtml`"])
    unidecode(["`unidecode`"])

    subgraph ext_test [--extra test]
        pytest{{"`pytest >=9`"}}
        pytest_xdist{{"`pytest-xdist >=3.7`"}}
        pytest_github_actions_annotate_failures{{"`pytest-github-actions-annotate-failures >=0.2`"}}
        pytest_randomly{{"`pytest-randomly >=3.15`"}}
    end

    subgraph ext_typing [--extra typing]
        types_requests{{"`types-requests >=2.32.0.20240622`"}}
    end

    blog ==>|" >=4.10 "| pelican
    blog ==>|" >=5 "| plumage
    blog ==>|" >=2.20 "| pygments
    blog ==>|" >=3 "| markdown_it_py
    blog ==>|" >=1.1 "| pelican_search
    blog ==>|" >=1.2.2 "| pelican_seo
    blog ==>|" >=1.2 "| pelican_neighbors
    blog ==>|" >=1.1 "| pelican_sitemap
    blog ==>|" >=2.0.7 "| typogrify
    pelican --> docutils
    pelican --> pygments
    pelican --> jinja2
    pelican --> rich
    pelican --> feedgenerator
    pelican --> python_dateutil
    pelican --> tzdata
    pelican --> watchfiles
    pelican --> blinker
    pelican --> markdown
    pelican --> ordered_set
    pelican --> unidecode
    plumage --> pelican
    plumage --> pelican_myst_reader
    plumage --> pygments
    plumage --> pyquery
    plumage --> pelican_webassets
    plumage --> cssmin
    plumage --> libsass
    plumage --> pynpm
    pytest --> pygments
    pytest --> colorama
    pytest --> packaging
    pytest --> iniconfig
    pytest --> pluggy
    markdown_it_py --> mdurl
    pytest_xdist --> pytest
    pytest_xdist --> execnet
    pytest_xdist --> psutil
    pelican_search --> pelican
    pelican_search --> rtoml
    pelican_seo --> pelican
    pelican_seo --> beautifulsoup4
    pelican_neighbors --> pelican
    pelican_sitemap --> pelican
    pytest_github_actions_annotate_failures --> pytest
    pytest_randomly --> pytest
    types_requests --> urllib3
    typogrify --> smartypants
    pelican_myst_reader --> pelican
    pelican_myst_reader --> myst_parser
    pelican_myst_reader --> docutils
    pelican_myst_reader --> sphinxcontrib_bibtex
    pelican_myst_reader --> beautifulsoup4
    pelican_myst_reader --> pyyaml
    pelican_myst_reader --> markdown_word_count
    beautifulsoup4 --> typing_extensions
    beautifulsoup4 --> soupsieve
    jinja2 --> markupsafe
    pyquery --> cssselect
    pyquery --> lxml
    rich --> pygments
    rich --> markdown_it_py
    feedgenerator --> tzdata
    pelican_webassets --> pelican
    python_dateutil --> six
    watchfiles --> anyio
    myst_parser --> sphinx
    myst_parser --> docutils
    myst_parser --> markdown_it_py
    myst_parser --> jinja2
    myst_parser --> pyyaml
    myst_parser --> mdit_py_plugins
    sphinxcontrib_bibtex --> sphinx
    sphinxcontrib_bibtex --> docutils
    sphinxcontrib_bibtex --> pybtex
    sphinxcontrib_bibtex --> pybtex_docutils
    anyio --> idna
    anyio --> typing_extensions
    sphinx --> docutils
    sphinx --> pygments
    sphinx --> requests
    sphinx --> jinja2
    sphinx --> colorama
    sphinx --> packaging
    sphinx --> roman_numerals_py
    sphinx --> alabaster
    sphinx --> babel
    sphinx --> imagesize
    sphinx --> snowballstemmer
    sphinx --> sphinxcontrib_applehelp
    sphinx --> sphinxcontrib_devhelp
    sphinx --> sphinxcontrib_htmlhelp
    sphinx --> sphinxcontrib_jsmath
    sphinx --> sphinxcontrib_qthelp
    sphinx --> sphinxcontrib_serializinghtml
    pybtex --> pyyaml
    pybtex --> latexcodec
    pybtex_docutils --> docutils
    pybtex_docutils --> pybtex
    mdit_py_plugins --> markdown_it_py
    requests --> idna
    requests --> urllib3
    requests --> certifi
    requests --> charset_normalizer
    roman_numerals_py --> roman_numerals
    blog -.-> ext_test
    blog -.-> ext_typing

    click alabaster "https://pypi.org/project/alabaster/" _blank
    click anyio "https://pypi.org/project/anyio/" _blank
    click babel "https://pypi.org/project/babel/" _blank
    click beautifulsoup4 "https://pypi.org/project/beautifulsoup4/" _blank
    click blinker "https://pypi.org/project/blinker/" _blank
    click blog "https://pypi.org/project/blog/" _blank
    click certifi "https://pypi.org/project/certifi/" _blank
    click charset_normalizer "https://pypi.org/project/charset-normalizer/" _blank
    click colorama "https://pypi.org/project/colorama/" _blank
    click cssmin "https://pypi.org/project/cssmin/" _blank
    click cssselect "https://pypi.org/project/cssselect/" _blank
    click docutils "https://pypi.org/project/docutils/" _blank
    click execnet "https://pypi.org/project/execnet/" _blank
    click feedgenerator "https://pypi.org/project/feedgenerator/" _blank
    click idna "https://pypi.org/project/idna/" _blank
    click imagesize "https://pypi.org/project/imagesize/" _blank
    click iniconfig "https://pypi.org/project/iniconfig/" _blank
    click jinja2 "https://pypi.org/project/jinja2/" _blank
    click latexcodec "https://pypi.org/project/latexcodec/" _blank
    click libsass "https://pypi.org/project/libsass/" _blank
    click lxml "https://pypi.org/project/lxml/" _blank
    click markdown "https://pypi.org/project/markdown/" _blank
    click markdown_it_py "https://pypi.org/project/markdown-it-py/" _blank
    click markdown_word_count "https://pypi.org/project/markdown-word-count/" _blank
    click markupsafe "https://pypi.org/project/markupsafe/" _blank
    click mdit_py_plugins "https://pypi.org/project/mdit-py-plugins/" _blank
    click mdurl "https://pypi.org/project/mdurl/" _blank
    click myst_parser "https://pypi.org/project/myst-parser/" _blank
    click ordered_set "https://pypi.org/project/ordered-set/" _blank
    click packaging "https://pypi.org/project/packaging/" _blank
    click pelican "https://pypi.org/project/pelican/" _blank
    click pelican_myst_reader "https://pypi.org/project/pelican-myst-reader/" _blank
    click pelican_neighbors "https://pypi.org/project/pelican-neighbors/" _blank
    click pelican_search "https://pypi.org/project/pelican-search/" _blank
    click pelican_seo "https://pypi.org/project/pelican-seo/" _blank
    click pelican_sitemap "https://pypi.org/project/pelican-sitemap/" _blank
    click pelican_webassets "https://pypi.org/project/pelican-webassets/" _blank
    click pluggy "https://pypi.org/project/pluggy/" _blank
    click plumage "https://pypi.org/project/plumage/" _blank
    click psutil "https://pypi.org/project/psutil/" _blank
    click pybtex "https://pypi.org/project/pybtex/" _blank
    click pybtex_docutils "https://pypi.org/project/pybtex-docutils/" _blank
    click pygments "https://pypi.org/project/pygments/" _blank
    click pynpm "https://pypi.org/project/pynpm/" _blank
    click pyquery "https://pypi.org/project/pyquery/" _blank
    click pytest "https://pypi.org/project/pytest/" _blank
    click pytest_github_actions_annotate_failures "https://pypi.org/project/pytest-github-actions-annotate-failures/" _blank
    click pytest_randomly "https://pypi.org/project/pytest-randomly/" _blank
    click pytest_xdist "https://pypi.org/project/pytest-xdist/" _blank
    click python_dateutil "https://pypi.org/project/python-dateutil/" _blank
    click pyyaml "https://pypi.org/project/pyyaml/" _blank
    click requests "https://pypi.org/project/requests/" _blank
    click rich "https://pypi.org/project/rich/" _blank
    click roman_numerals "https://pypi.org/project/roman-numerals/" _blank
    click roman_numerals_py "https://pypi.org/project/roman-numerals-py/" _blank
    click rtoml "https://pypi.org/project/rtoml/" _blank
    click six "https://pypi.org/project/six/" _blank
    click smartypants "https://pypi.org/project/smartypants/" _blank
    click snowballstemmer "https://pypi.org/project/snowballstemmer/" _blank
    click soupsieve "https://pypi.org/project/soupsieve/" _blank
    click sphinx "https://pypi.org/project/sphinx/" _blank
    click sphinxcontrib_applehelp "https://pypi.org/project/sphinxcontrib-applehelp/" _blank
    click sphinxcontrib_bibtex "https://pypi.org/project/sphinxcontrib-bibtex/" _blank
    click sphinxcontrib_devhelp "https://pypi.org/project/sphinxcontrib-devhelp/" _blank
    click sphinxcontrib_htmlhelp "https://pypi.org/project/sphinxcontrib-htmlhelp/" _blank
    click sphinxcontrib_jsmath "https://pypi.org/project/sphinxcontrib-jsmath/" _blank
    click sphinxcontrib_qthelp "https://pypi.org/project/sphinxcontrib-qthelp/" _blank
    click sphinxcontrib_serializinghtml "https://pypi.org/project/sphinxcontrib-serializinghtml/" _blank
    click types_requests "https://pypi.org/project/types-requests/" _blank
    click typing_extensions "https://pypi.org/project/typing-extensions/" _blank
    click typogrify "https://pypi.org/project/typogrify/" _blank
    click tzdata "https://pypi.org/project/tzdata/" _blank
    click unidecode "https://pypi.org/project/unidecode/" _blank
    click urllib3 "https://pypi.org/project/urllib3/" _blank
    click watchfiles "https://pypi.org/project/watchfiles/" _blank

    style blog stroke-width:3px
    style markdown_it_py stroke-width:3px
    style pelican stroke-width:3px
    style pelican_neighbors stroke-width:3px
    style pelican_search stroke-width:3px
    style pelican_seo stroke-width:3px
    style pelican_sitemap stroke-width:3px
    style plumage stroke-width:3px
    style pygments stroke-width:3px
    style pytest stroke-width:3px
    style pytest_github_actions_annotate_failures stroke-width:3px
    style pytest_randomly stroke-width:3px
    style pytest_xdist stroke-width:3px
    style types_requests stroke-width:3px
    style typogrify stroke-width:3px

    style primary-deps fill:#1565C020,stroke:#42A5F5
    style ext_test fill:#7B1FA220,stroke:#BA68C8
    style ext_typing fill:#7B1FA220,stroke:#BA68C8
